version: "3"
services:
    hub:
        image: selenium/hub:3.14
        ports: 
            - "4444:4444"
    chrome:
        image: selenium/node-chrome:3.14
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
    firefox:
        image: selenium/node-firefox:3.14
        shm_size: '1gb'
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
    spethomepage-module:
        image: aadithyaks/selenium-docker
        depends_on:
            - chrome
            - firefox
        environment:
            - BROWSER=chrome
            - HUB_HOST=hub
            - MODULE=spethomepage-module.xml
        volumes:
            - ./output/spethomepage-testresults:/usr/share/bfsdemo/test-output
    spetsearchpage-module:
        image: aadithyaks/selenium-docker
        depends_on:
            - chrome
            - firefox
        environment:
            - BROWSER=chrome
            - HUB_HOST=hub
            - MODULE=spetsearchpage-module.xml
        volumes:
            - ./output/spetsearchpage-testresults:/usr/share/bfsdemo/test-output